name: Github_Actions_Joan_Nacher

on:
  push:
    branches: [ main ]

jobs:
  Linter_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0

      - name: Dependencies linter
        run: npm ci

      - name : Executar linter
        run: npm run lint

  Cypress_job:
    needs: Linter_job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Tests de Cypress
        uses: cypress-io/github-action@v6.10.2
        id: cypress
        continue-on-error: true
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
      
      - name: Guardar logs a result.txt
        run: echo "${{ steps.cypress.outcome }}" > result.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: resultat
          path: result.txt

    Add_badge_job:
      needs: Cypress_job
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Download a Build Artifact
          uses: actions/download-artifact@v5.0.0
          with:
            name: resultat
            path: result.txt

        - name: Generar output amb el resultat
          id: generate_output
          run: |
            echo "::set-output name=cypress_outcome::$(cat result.txt)"

        - name: Executar action 
          uses: ./github/actions/add-badge
          with: 
            cypress_outcome: ${{ steps.generate_output.outputs.cypress_outcome }}
        
        - name: Publicar canvis
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md 
            git commit -m "Update del README"
            git push