name: Github_Actions_Joan_Nacher

on:
  push:
    branches: [ main ]

jobs:
  Linter_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0

      - name: Dependencies linter
        run: npm ci

      - name : Executar linter
        run: npm run lint
